"""Фразы персоны: киноклуб: вотчлист, голосование, оценки, форум."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- киноклуб: /movie add ---
    _spec(
        "cinema.pick_prompt",
        "cinema",
        "template",
        "Нашла {count} — уточни:",
        label="/movie add: найдено несколько, уточнить",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.add_need_title",
        "cinema",
        "str",
        "Название-то напиши.",
        label="/movie add: пустое название",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.add_duplicate",
        "cinema",
        "template",
        "**{title}** уже в вотчлисте — голосуй за него 👍.",
        label="/movie add: уже в вотчлисте",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.add_limit",
        "cinema",
        "template",
        "Вотчлист переполнен ({max}). Сначала посмотрите что-нибудь.",
        label="/movie add: вотчлист переполнен",
        placeholders=("max",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.card_proposer",
        "cinema",
        "template",
        "-# Предложил {proposer} · голосуйте кнопками",
        label="Карточка фильма: кто предложил",
        placeholders=("proposer",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.card_footer",
        "cinema",
        "template",
        "👍 {up} · 👎 {down} · счёт {score}",
        label="Карточка фильма: футер со счётом",
        placeholders=("up", "down", "score"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.card_send_failed",
        "cinema",
        "str",
        "Не смогла отправить карточку.",
        label="Карточка фильма не отправилась",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.add_ok",
        "cinema",
        "template",
        "В вотчлисте: **{title}**",
        label="/movie add: добавлено",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    # --- киноклуб: голосование за карточку ---
    _spec(
        "cinema.vote_gone",
        "cinema",
        "str",
        "Этот фильм уже не в вотчлисте.",
        label="Голос: фильма уже нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.vote_up",
        "cinema",
        "str",
        "👍 Учтён.",
        label="Голос: за (учтён)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.vote_down",
        "cinema",
        "str",
        "👎 Учтён.",
        label="Голос: против (учтён)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.vote_removed",
        "cinema",
        "str",
        "Голос снят.",
        label="Голос снят",
        allowed_modes=STATIC_MODES,
    ),
    # --- киноклуб: /movie list, remove, watched, top ---
    _spec(
        "cinema.list_empty",
        "cinema",
        "str",
        "Вотчлист пуст — `/movie add` в помощь.",
        label="/movie list: пусто",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.list_more",
        "cinema",
        "template",
        "…и ещё {count}",
        label="/movie list: «…и ещё N»",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.list_title",
        "cinema",
        "template",
        "🎬 Вотчлист ({count})",
        label="/movie list: заголовок",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.list_footer",
        "cinema",
        "str",
        "/movienight start — устроить киновечер",
        label="/movie list: футер",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.pick_from_hints",
        "cinema",
        "str",
        "Выбери фильм из подсказок.",
        label="Выбор фильма: только из подсказок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.remove_ok",
        "cinema",
        "template",
        "🗑️ Убрала: **{title}**",
        label="/movie remove: убрано",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.remove_not_found",
        "cinema",
        "str",
        "Такого фильма в вотчлисте нет.",
        label="/movie remove: не найдено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.remove_forbidden",
        "cinema",
        "str",
        "Убирать может предложивший или администратор.",
        label="/movie remove: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.watched_bad",
        "cinema",
        "str",
        "Этот фильм не в вотчлисте или уже оценивается.",
        label="/movie watched: нельзя открыть оценки",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_opened",
        "cinema",
        "str",
        "Открыла сбор оценок.",
        label="Сбор оценок открыт (подтверждение)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.top_empty",
        "cinema",
        "str",
        "Пока ничего не посмотрели. Всё впереди.",
        label="/movie top: пусто",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.top_title",
        "cinema",
        "template",
        "🏆 Золотой фонд ({count})",
        label="/movie top: заголовок",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    # --- киноклуб: /movienight ---
    _spec(
        "cinema.night_bad_time",
        "cinema",
        "str",
        "Не поняла время. Форматы: `20:30`, `завтра 19:00`, `12.07 21:00`; минимум за 15 минут.",
        label="/movienight start: не разобрать время",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_busy",
        "cinema",
        "str",
        "Киновечер уже назначен — `/movienight cancel`, если передумали.",
        label="/movienight start: уже назначен",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_empty",
        "cinema",
        "str",
        "Вотчлист пуст — сначала `/movie add`.",
        label="/movienight start: вотчлист пуст",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_poll_title",
        "cinema",
        "str",
        "🍿 Киновечер: выбираем фильм",
        label="Киновечер: заголовок опроса",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_session",
        "cinema",
        "template",
        "**Сеанс:** {when} ({rel})",
        label="Киновечер: строка сеанса",
        placeholders=("when", "rel"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_vote_until",
        "cinema",
        "template",
        "**Голосование до** {when} ({rel})",
        label="Киновечер: строка «голосование до»",
        placeholders=("when", "rel"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_poll_footer",
        "cinema",
        "str",
        "Один голос на человека; можно передумать.",
        label="Киновечер: футер опроса",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_poll_send_failed",
        "cinema",
        "str",
        "Не смогла отправить опрос.",
        label="Киновечер: опрос не отправился",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_announced",
        "cinema",
        "str",
        "Киновечер объявлен. 🍿",
        label="Киновечер объявлен (подтверждение)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_cancel_ok",
        "cinema",
        "str",
        "Отменила. Значит, в другой раз.",
        label="/movienight cancel: отменено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_cancel_none",
        "cinema",
        "str",
        "Отменять нечего — киновечер не назначен.",
        label="/movienight cancel: нечего отменять",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_cancel_forbidden",
        "cinema",
        "str",
        "Отменять может устроивший или администратор.",
        label="/movienight cancel: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_vote_closed",
        "cinema",
        "str",
        "Голосование уже закрыто.",
        label="Киновечер: голосование закрыто",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.movie_fallback",
        "cinema",
        "str",
        "фильм",
        label="Запасное слово «фильм» (когда название неизвестно)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.night_vote_ok",
        "cinema",
        "template",
        "Голос за **{title}** принят.",
        label="Киновечер: голос принят",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    # --- киноклуб: оценки ---
    _spec(
        "cinema.rating_already_open",
        "cinema",
        "str",
        "Оценки уже открыты или киновечер не активен.",
        label="Оценки: уже открыты / вечер не активен",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_closed",
        "cinema",
        "str",
        "Сбор оценок уже закрыт.",
        label="Оценки: сбор закрыт",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_footer",
        "cinema",
        "template",
        "Оценок: {count} · Отзывов: {reviews}",
        label="Оценки: футер (счётчики)",
        placeholders=("count", "reviews"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_recorded",
        "cinema",
        "template",
        "Записала: **{score}/10**.",
        label="Оценка записана",
        placeholders=("score",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.review_recorded",
        "cinema",
        "str",
        "Отзыв записан — появится в ветке под итогами. ✂️👁🖤",
        label="Отзыв записан",
        allowed_modes=STATIC_MODES,
    ),
    # --- киноклуб: внутренности (сервис/форум/виджеты) ---
    _spec(
        "cinema.winner_comment_instruction",
        "cinema",
        "template",
        "Киноклуб сервера голосованием выбрал фильм для совместного "
        "просмотра: «{title}»{year}. Прокомментируй выбор одной-двумя "
        "фразами в своём стиле.",
        label="AI-инструкция: комментарий к победителю опроса",
        placeholders=("title", "year"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.verdict_instruction",
        "cinema",
        "template",
        "Киноклуб сервера посмотрел фильм «{title}»{year}. Ты тоже смотрела. "
        "Ответь СТРОГО в формате «N/10 — комментарий», где N — твоя оценка "
        "от 1 до 10, а комментарий — одна колкая фраза-рецензия в твоём стиле.",
        label="AI-инструкция: вердикт Попоси после просмотра",
        placeholders=("title", "year"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.poll_no_votes",
        "cinema",
        "str",
        "🍿 Никто не проголосовал — киновечер отменяется. Посмотрю одна. Мне не привыкать.",
        label="Киновечер: никто не проголосовал",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.winner_title",
        "cinema",
        "template",
        "🏆 Смотрим: {title}",
        label="Победитель опроса: заголовок",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.winner_votes",
        "cinema",
        "template",
        "-# Голосов: {votes}. После просмотра жмите кнопку ниже.",
        label="Победитель опроса: строка голосов",
        placeholders=("votes",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.remind",
        "cinema",
        "template",
        "🍿 Время. Смотрим **{title}** — как закончите, жмите "
        "«Мы посмотрели» под анонсом. Я уже с чаем.",
        label="Киновечер: напоминание о сеансе",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_title",
        "cinema",
        "template",
        "⭐ Оцениваем: {title}",
        label="Сбор оценок: заголовок карточки",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.rating_body",
        "cinema",
        "template",
        "Кнопки 1–10 — твоя оценка (можно передумать), "
        "✍️ **Отзыв** — пара слов рецензии.\nИтоги {when}.",
        label="Сбор оценок: тело карточки",
        placeholders=("when",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.finalized_forum",
        "cinema",
        "template",
        "🎬 **{title}** — в золотом фонде. Итоги и рецензии: {link}",
        label="Итоги: указатель на пост в золотом фонде",
        placeholders=("title", "link"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.summary_score_field",
        "cinema",
        "str",
        "⭐ Оценка сервера",
        label="Сводка: поле «Оценка сервера»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.summary_score_value",
        "cinema",
        "template",
        "**{avg}/10** · {count} оцен.",
        label="Сводка: значение оценки сервера",
        placeholders=("avg", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.summary_no_ratings",
        "cinema",
        "str",
        "оценок нет",
        label="Сводка: оценок нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.summary_verdict_field",
        "cinema",
        "str",
        "✂️👁🖤 Вердикт Попоси",
        label="Сводка: поле «Вердикт Попоси»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.summary_footer",
        "cinema",
        "str",
        "Золотой фонд · /movie top",
        label="Сводка: футер",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "cinema.pick_taken",
        "cinema",
        "template",
        "Беру: **{title}**",
        label="Выбор фильма: взяла выбранный",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
]
