"""Фразы персоны: пер-серверные настройки (/config)."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- настройки: общий путь записи ---
    _spec(
        "config.apply_rejected",
        "config",
        "template",
        "Не приняла: {error}. `{key}` — {label}.",
        label="/config: значение отклонено (с ключом)",
        placeholders=("error", "key", "label"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.apply_ok",
        "config",
        "template",
        "✅ **{key}** = {value} (для этого сервера).",
        label="/config: настройка применена",
        placeholders=("key", "value"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.rejected_simple",
        "config",
        "template",
        "Не приняла: {error}.",
        label="/config: значение отклонено (кратко)",
        placeholders=("error",),
        allowed_modes=STATIC_MODES,
    ),
    # --- настройки: обзор (/config list · show) ---
    _spec(
        "config.list_title",
        "config",
        "str",
        "⚙️ Настройки сервера",
        label="/config list: заголовок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.list_footer",
        "config",
        "str",
        "🔧 — переопределено на сервере · · — глобальный дефолт",
        label="/config list: футер-легенда",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.no_setting",
        "config",
        "str",
        "Нет такой настройки. Смотри `/config list`.",
        label="/config show·reset: настройки нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.show_body",
        "config",
        "template",
        "{label}\n\n**Сейчас:** {current}{note}\n**Дефолт:** {default}{range}",
        label="/config show: тело карточки",
        placeholders=("label", "current", "note", "default", "range"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.show_overridden",
        "config",
        "str",
        " 🔧 (переопределено)",
        label="/config show: пометка «переопределено»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.show_default_note",
        "config",
        "str",
        " (дефолт)",
        label="/config show: пометка «дефолт»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.show_range",
        "config",
        "template",
        "\n**Диапазон:** {min}–{max}",
        label="/config show: строка диапазона",
        placeholders=("min", "max"),
        allowed_modes=STATIC_MODES,
    ),
    # --- настройки: типизированная запись (отказы по типу) ---
    _spec(
        "config.no_channel_setting",
        "config",
        "str",
        "Нет такой настройки-канала. Смотри `/config list`.",
        label="/config channel: настройки-канала нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.no_bool_setting",
        "config",
        "str",
        "Нет такой вкл/выкл-настройки. Смотри `/config list`.",
        label="/config toggle: булевой настройки нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.no_number_setting",
        "config",
        "str",
        "Нет такой числовой настройки. Смотри `/config list`.",
        label="/config number: числовой настройки нет",
        allowed_modes=STATIC_MODES,
    ),
    # --- настройки: роли и лимиты ---
    _spec(
        "config.roles_bad_thresholds",
        "config",
        "str",
        "Пороги — только целые числа через запятую/пробел.",
        label="/config roles: кривые пороги",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.roles_updated",
        "config",
        "template",
        "✅ Роли обновлены: {thresholds} порогов и {names} имён (для этого сервера).",
        label="/config roles: роли обновлены",
        placeholders=("thresholds", "names"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.limits_updated",
        "config",
        "template",
        "✅ Лимиты реплик обновлены ({count} уровней, для этого сервера).",
        label="/config limits: лимиты обновлены",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.roles_reset",
        "config",
        "str",
        "↩️ Пороги и имена ролей сброшены к дефолту.",
        label="/config roles reset: сброшено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.limits_reset",
        "config",
        "str",
        "↩️ Лимиты реплик сброшены к дефолту.",
        label="/config limits reset: сброшено",
        allowed_modes=STATIC_MODES,
    ),
    # --- настройки: сброс одного ключа ---
    _spec(
        "config.reset_done",
        "config",
        "template",
        "↩️ **{key}** сброшено к дефолту: {value}.",
        label="/config reset: сброшено к дефолту",
        placeholders=("key", "value"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "config.reset_noop",
        "config",
        "template",
        "**{key}** и так на дефолте: {value}.",
        label="/config reset: уже на дефолте",
        placeholders=("key", "value"),
        allowed_modes=STATIC_MODES,
    ),
]
