"""Фразы персоны: ночные находки: анонс, поход, /finds/collection/gift/walk."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- находки: анонс ---
    _spec(
        "finds.opener",
        "finds",
        "list",
        [
            "Я сегодня гуляла под мелким дождём около {place}. Заметила кое-что… интересное.",
            "Опять бродила ночью. Нашла кое-что, что может тебе понравиться.",
            "Иногда город сам подкидывает подарки. Сегодня был такой момент.",
            "Не удержалась. В старом районе кое-что блеснуло под фонарём.",
        ],
        label="Анонс находки: зачин (случайный)",
        placeholders=("place",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.announce_title",
        "finds",
        "str",
        "🌙 Ночная находка",
        label="Анонс находки: заголовок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.announce_body",
        "finds",
        "str",
        "Не обещаю, что оно всё ещё там — Токио быстрый. "
        "Но если хочешь, можешь сходить посмотреть.",
        label="Анонс находки: приглашение",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.announce_place",
        "finds",
        "template",
        "**Место:** {place}\n-# {place_flavor}",
        label="Анонс находки: строка места",
        placeholders=("place", "place_flavor"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.announce_footer",
        "finds",
        "str",
        "Одна попытка на находку. Заберёт первый, кому повезёт.",
        label="Анонс находки: футер",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.expired",
        "finds",
        "str",
        "-# 🌙 Опоздали. Токио быстрый — находки не ждут.",
        label="Приписка к протухшей находке",
        allowed_modes=STATIC_MODES,
    ),
    # --- находки: поход по кнопке ---
    _spec(
        "finds.claim_gone",
        "finds",
        "str",
        "Там уже пусто. Или кто-то успел раньше, или Токио забрал своё.",
        label="Поход: находку уже забрали",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_already",
        "finds",
        "str",
        "Ты уже ходил к этой находке. Второго шанса город не даёт.",
        label="Поход: повторная попытка",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_cooldown",
        "finds",
        "template",
        "Ноги ещё гудят после прошлого похода. Возвращайся {retry}.",
        label="Поход: кулдаун",
        placeholders=("retry",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_fail",
        "finds",
        "list",
        [
            "Пусто? Как неожиданно. Хотя… я же не говорила, что оно будет лежать "
            "и ждать именно тебя.",
            "Ничего? Жаль. В следующий раз смотри внимательнее.",
            "Пф. Пустые руки. Не расстраивайся, я тоже иногда возвращаюсь ни с чем. Хотя и реже.",
        ],
        label="Поход: неудача (случайная)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.points_tail",
        "finds",
        "template",
        "-# {delta} очков. Сейчас у тебя {total}.",
        label="Поход: приписка об очках при неудаче",
        placeholders=("delta", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_success_note",
        "finds",
        "template",
        "{item_emoji} **{item}** теперь в твоей коллекции (`/collection`). +{delta} очков.",
        label="Поход: личное подтверждение успеха",
        placeholders=("item_emoji", "item", "delta"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_taken_note",
        "finds",
        "template",
        "-# ✅ Забрал {user_mention} — {item_emoji} {item}",
        label="Поход: приписка к закрытому анонсу",
        placeholders=("user_mention", "item_emoji", "item"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.success_low",
        "finds",
        "str",
        "Хорошо. Ты его действительно забрал. Не ожидала.",
        label="Реакция на успех: низкий уровень отношений",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.success_mid",
        "finds",
        "str",
        "Неплохо. Это даже мило с твоей стороны.",
        label="Реакция на успех: средний уровень",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.success_high",
        "finds",
        "str",
        "…Ты правда пошёл туда ради этого? Хм. Спасибо. ✂️👁🖤",
        label="Реакция на успех: высокий уровень",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.success_legendary",
        "finds",
        "str",
        "…Стой. Ты нашёл ЭТО? Я запомню этот момент. Надолго. ✂️👁🖤",
        label="Реакция на успех: легендарная находка",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.claim_award",
        "finds",
        "template",
        "{user_mention} получает **+{delta}** очков ({rarity_emoji} {rarity} находка).",
        label="Публичное объявление успеха: строка очков",
        placeholders=("user_mention", "delta", "rarity_emoji", "rarity"),
        allowed_modes=STATIC_MODES,
    ),
    # --- находки: /finds, /collection, /gift, /walk ---
    _spec(
        "finds.none_active",
        "finds",
        "str",
        "Сейчас находок нет. Я хожу гулять, когда сама захочу.",
        label="/finds: активных находок нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.active_title",
        "finds",
        "str",
        "🌙 Активная находка",
        label="/finds: заголовок карточки",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.active_body",
        "finds",
        "template",
        "**Место:** {place}\n-# {place_flavor}\n\nПропадёт {expires}.",
        label="/finds: тело карточки",
        placeholders=("place", "place_flavor", "expires"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.active_jump",
        "finds",
        "template",
        "[К анонсу]({url})",
        label="/finds: подпись ссылки на анонс",
        placeholders=("url",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.collection_empty",
        "finds",
        "str",
        "Пока пусто. Следи за моими ночными прогулками — и успевай первым.",
        label="/collection: пустая коллекция",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.collection_title",
        "finds",
        "template",
        "🗃️ Коллекция ({count})",
        label="/collection: заголовок",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.collection_gifted_mark",
        "finds",
        "str",
        " · 🎁 подарено мне",
        label="/collection: пометка подаренного",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.gift_no_item",
        "finds",
        "str",
        "У тебя нет такого предмета. Дарить чужое — не твой уровень.",
        label="/gift: предмета нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.gift",
        "finds",
        "dict",
        {
            "common": "Ты серьёзно решил мне это подарить? …Ладно. Я приму. И запомню.",
            "uncommon": "Хм. У тебя неплохой вкус. Приму. И да — я запомню.",
            "rare": "…Это правда мне? Такое я не забываю. Спасибо. 🖤",
            "legendary": "…Я не знаю, что сказать. Это со мной навсегда. Как и этот момент. ✂️👁🖤",
        },
        label="/gift: реакция по редкости (common/uncommon/rare/legendary)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.gift_award",
        "finds",
        "template",
        "{user_mention} получает **+{bonus}** очков.",
        label="/gift: строка очков",
        placeholders=("user_mention", "bonus"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_cooldown",
        "finds",
        "template",
        "Я тебе не такси. Следующая прогулка — {retry}.",
        label="/walk: кулдаун",
        placeholders=("retry",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_poor",
        "finds",
        "template",
        "Прогулка стоит **{cost}** очков, у тебя {total}. Сначала заслужи.",
        label="/walk: не хватает очков",
        placeholders=("cost", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_fail",
        "finds",
        "list",
        [
            "Прогулялась впустую. Город сегодня жадный. Бывает.",
            "Ничего. Даже кот куда-то делся. Не мой вечер — и не твой.",
        ],
        label="/walk: неудача (случайная)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_fail_tail",
        "finds",
        "template",
        "-# −{cost} очков за прогулку. Сейчас у тебя {total}.",
        label="/walk: приписка об очках при неудаче",
        placeholders=("cost", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_success",
        "finds",
        "list",
        [
            "Прогулялась. Дождь, фонари, один подозрительный кот. И вот — держи.",
            "Сходила. Ради тебя, между прочим. Смотри, что принесла.",
        ],
        label="/walk: успех (случайный)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "finds.walk_success_tail",
        "finds",
        "template",
        "{item_emoji} **{item}** — в твоей коллекции.\n"
        "-# Итог: {sign}{delta} очков (прогулка −{cost}, находка сверху). "
        "Сейчас у тебя {total}.",
        label="/walk: итог успеха",
        placeholders=("item_emoji", "item", "sign", "delta", "cost", "total"),
        allowed_modes=STATIC_MODES,
    ),
]
