"""Фразы персоны: развлечения: темы, кости, профиль, ДР, правила, /send, /remind."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- развлечения: темы для разговора и монетка ---
    _spec(
        "fun.topics",
        "fun",
        "list",
        [
            "Какая игра тебя по-настоящему удивила за последний год?",
            "Кофе или чай — и почему твой выбор правильный?",
            "Лучший саундтрек из игры, который ты слушаешь отдельно?",
            "Есть ли фильм, который все хвалят, а тебе не зашёл?",
            "Какую способность из игр ты бы забрал в реальную жизнь?",
            "Самая переоценённая вещь в интернете сейчас?",
            "Что ты умеешь делать лучше большинства здесь?",
            "Идеальный вечер: расписание по пунктам.",
            "Какой босс в играх заставил тебя страдать сильнее всего?",
            "Если бы завтра переезд в любую страну — куда и почему?",
            "Какая книга или манга изменила твой взгляд на что-то?",
            "Дождь за окном: уют или тоска?",
            "Какую еду ты можешь есть бесконечно?",
            "Самый бесполезный факт, который ты знаешь?",
            "Что бы ты сказал себе пять лет назад?",
        ],
        label="/topic: темы для разговора (случайная)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.coin_sides",
        "fun",
        "list",
        ["Орёл 🦅", "Решка 🪙"],
        label="/coinflip: стороны монеты (случайная)",
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: кости ---
    _spec(
        "fun.dice_too_many",
        "fun",
        "template",
        "Больше {max} игроков — это уже лотерея, а не кости. Сократи список.",
        label="/dice: слишком много игроков",
        placeholders=("max",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_bots_only",
        "fun",
        "str",
        "Боты в кости не играют — у них всё по алгоритму. Позови живых.",
        label="/dice: в дуэли только боты",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_duel_title",
        "fun",
        "template",
        "🎲 **Дуэль на кубиках** (d{sides})",
        label="/dice: заголовок дуэли",
        placeholders=("sides",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_round",
        "fun",
        "template",
        "**Раунд {round}:**",
        label="/dice: подпись раунда (перед бросками)",
        placeholders=("round",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_winner",
        "fun",
        "template",
        "🏆 Победа: {winner} — выбросил **{best}**!",
        label="/dice: победитель дуэли",
        placeholders=("winner", "best"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_tie",
        "fun",
        "template",
        "Ничья между {names} — перебрасываю. 🎲",
        label="/dice: ничья, переброс",
        placeholders=("names",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.dice_stalemate",
        "fun",
        "template",
        "{rounds} раундов подряд ничья. Судьба говорит вам дружить. Мне надоело.",
        label="/dice: бесконечная ничья",
        placeholders=("rounds",),
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: профиль ---
    _spec(
        "fun.profile_bot",
        "fun",
        "str",
        "У ботов нет души. И профиля.",
        label="/profile: у ботов нет профиля",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_no_status",
        "fun",
        "str",
        "☕ Случайный прохожий (пока без статуса)",
        label="/profile: статуса ещё нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_1",
        "fun",
        "template",
        "Это ты… Напомни, как тебя зовут?",
        label="/profile: обращение (ур. 1)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_2",
        "fun",
        "template",
        "Это ты, {name}… Я помню каждый твой шаг.",
        label="/profile: обращение (ур. 2)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_3",
        "fun",
        "template",
        "Это ты, {name}… Я помню каждый твой шаг.",
        label="/profile: обращение (ур. 3)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_4",
        "fun",
        "template",
        "О, {name}. Я как раз о тебе думала. Не льсти себе.",
        label="/profile: обращение (ур. 4)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_5",
        "fun",
        "template",
        "{name}. Кофе уже остыл, пока ты собирался зайти.",
        label="/profile: обращение (ур. 5)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_6",
        "fun",
        "template",
        "{name}. Моё вечернее расписание знает твоё имя.",
        label="/profile: обращение (ур. 6)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_opener_7",
        "fun",
        "template",
        "{name}. Кресло у окна — твоё.",
        label="/profile: обращение (ур. 7)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_attitude",
        "fun",
        "dict",
        {
            "1": "настороженное",
            "2": "сдержанное",
            "3": "нейтральное",
            "4": "тёплое",
            "5": "доверительное",
            "6": "близкое",
            "7": "ты — единственный",
        },
        label="/profile: «Моё отношение» по уровню (1–7)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_footers",
        "fun",
        "dict",
        {
            "1": "Пока ты просто имя в списке.",
            "2": "Ты уже не просто имя в списке.",
            "3": "Ты уже не просто имя в списке.",
            "4": "С тобой этот дом немного теплее.",
            "5": "С тобой этот дом немного теплее.",
            "6": "Виски на двоих — это про тебя.",
            "7": "✂️👁🖤",
        },
        label="/profile: футер по уровню (1–7)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_attachment",
        "fun",
        "str",
        "Привязанность",
        label="/profile: поле «Привязанность»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_activity",
        "fun",
        "str",
        "Активность",
        label="/profile: поле «Активность»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_showcase",
        "fun",
        "str",
        "Витрина",
        label="/profile: поле «Витрина»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_known",
        "fun",
        "str",
        "Что я знаю о тебе…",
        label="/profile: поле «Что я знаю о тебе…»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_attitude",
        "fun",
        "str",
        "Моё отношение",
        label="/profile: поле «Моё отношение»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_birthday",
        "fun",
        "str",
        "День рождения",
        label="/profile: поле «День рождения»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_field_badges",
        "fun",
        "str",
        "✨ Отметки",
        label="/profile: поле «✨ Отметки»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_attachment",
        "fun",
        "template",
        "{role_name}\n`{bar}` **{points}** очков",
        label="/profile: строка привязанности (роль/бар/очки)",
        placeholders=("role_name", "bar", "points"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_to_next",
        "fun",
        "template",
        "*До следующего статуса: {remaining}*",
        label="/profile: сколько очков до следующего статуса",
        placeholders=("remaining",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_deep_dialogs",
        "fun",
        "template",
        "🍷 Долгих разговоров: **{count}**",
        label="/profile: долгих разговоров",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_known_interests",
        "fun",
        "template",
        "• Интересы: {interests}",
        label="/profile: строка интересов",
        placeholders=("interests",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_known_season",
        "fun",
        "template",
        "• Любимое время года: {season}",
        label="/profile: строка времени года",
        placeholders=("season",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_known_empty",
        "fun",
        "str",
        "• Пока почти ничего. Исправь это.",
        label="/profile: о тебе почти ничего не известно",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.profile_badges",
        "fun",
        "dict",
        {
            "survey": "📋 Анкета",
            "birthday": "🎂 Дата в календаре",
            "deep": "🍷 Вечерние разговоры",
            "exclusive": "✂️👁🖤 Кресло у окна",
        },
        label="/profile: отметки (survey/birthday/deep/exclusive)",
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: last_seen (строка «когда говорил со мной») ---
    _spec(
        "fun.last_seen_never",
        "fun",
        "str",
        "ещё ни разу не заговаривал со мной",
        label="/profile: ни разу не заговаривал",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.last_seen_today",
        "fun",
        "str",
        "говорил со мной сегодня",
        label="/profile: говорил сегодня",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.last_seen_yesterday",
        "fun",
        "str",
        "говорил со мной вчера",
        label="/profile: говорил вчера",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.last_seen_days",
        "fun",
        "template",
        "говорил со мной {days} дн. назад",
        label="/profile: говорил N дней назад",
        placeholders=("days",),
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: витрина профиля ---
    _spec(
        "fun.showcase_finds",
        "fun",
        "template",
        "🗃 Находки: {parts}",
        label="/profile витрина: находки",
        placeholders=("parts",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.showcase_finds_gifted",
        "fun",
        "template",
        " · 🎁 подарено мне: {gifted}",
        label="/profile витрина: сколько подарено",
        placeholders=("gifted",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.showcase_music",
        "fun",
        "template",
        "🎧 Лайкнутых треков: **{count}**",
        label="/profile витрина: лайкнутые треки",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.showcase_cinema",
        "fun",
        "template",
        "🎬 Кино: предложено **{proposed}**, оценок **{ratings}**",
        label="/profile витрина: кино",
        placeholders=("proposed", "ratings"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.showcase_cinema_avg",
        "fun",
        "template",
        " (средняя {avg})",
        label="/profile витрина: средняя оценка кино",
        placeholders=("avg",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.showcase_voice",
        "fun",
        "template",
        "🎙 В войсе со мной: **{hours} ч**",
        label="/profile витрина: часы в войсе",
        placeholders=("hours",),
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: день рождения ---
    _spec(
        "fun.birthday_invalid",
        "fun",
        "str",
        "Такой даты не существует. Попробуй ещё раз, календарь в помощь.",
        label="/birthday: такой даты нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.birthday_saved",
        "fun",
        "template",
        "Записала: {day}.{month}. Я помню дни рождения своих гостей — теперь и твой. ✂️👁🖤",
        label="/birthday: дата записана",
        placeholders=("day", "month"),
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: правила и статистика ---
    _spec(
        "fun.rules_title",
        "fun",
        "str",
        "",  # пусто: заголовок вынесен в описание через `## ...` (кастом-эмодзи в title не рендерятся)
        label="/rules: заголовок embed (пусто = заголовок в тексте)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.rules_text",
        "fun",
        "str",
        "## <:rules:1535107542517153812> Правила\n"
        "*Считай, что зашёл ко мне в гостиную. Здесь тепло, играет музыка и "
        "наливают приличный кофе — но у каждого дома свой уклад. Мой — вот такой. "
        "Прочти один раз, внимательно. Повторять я не люблю.*\n"
        "\n"
        "**1 · Уважение**\n"
        "Сарказм — это нормально. Травля, унижения и переходы на личности — нет. "
        "Взрослый человек видит эту границу без подсказок.\n"
        "\n"
        "**2 · Контент**\n"
        "NSFW — только в специально отведённых каналах. В остальных местах без "
        "NSFW, шок-контента, крови, жести и политики. Мне не нужен этот шум в "
        "общем пространстве.\n"
        "\n"
        "**3 · Тишина**\n"
        "Спам, флуд, капс и пинги без причины — это неуважение. За это — мут. "
        "Без долгих предупреждений.\n"
        "\n"
        "**4 · Реклама**\n"
        "Чужие ссылки, приглашения на сервера и любая реклама — только с "
        "разрешения администрации. Твой проект — не забота этого чата.\n"
        "\n"
        "**5 · Имя и лицо**\n"
        "Ник и аватар должны быть читаемыми и приличными. Первое впечатление "
        "ты производишь ими, ещё до первого слова.\n"
        "\n"
        "**6 · Роли**\n"
        "Роли не выпрашивают. Как и кому их давать — решаю я. Просто будь "
        "интересным человеком. Остальное придёт само.\n"
        "\n"
        "**7 · Голосовые и личные сообщения**\n"
        "То, что нельзя писать в чате, нельзя говорить в войсе и писать "
        "участникам в личку. Нарушение в ЛС = нарушение на сервере.\n"
        "\n"
        "**8 · Последнее слово**\n"
        "Решение администрации и модераторов — финальное. Споры с модерацией "
        "заканчиваются быстро.\n"
        "\n"
        "Соблюдать несложно. А если ты не скучный — здесь бывает даже очень "
        "хорошо.\n"
        "✂️👁🖤\n"
        "-# Правила может обновить администрация сервера.",
        label="/rules: текст правил",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.rules_published",
        "fun",
        "template",
        "Готово. Правила теперь в {channel}.",
        label="/rules: подтверждение публикации (эфемерно)",
        placeholders=("channel",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.rules_no_perm",
        "fun",
        "template",
        "Не могу писать в {channel} — проверь мои права.",
        label="/rules: нет прав писать в канал",
        placeholders=("channel",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_field_members",
        "fun",
        "str",
        "Участников",
        label="/serverstats: поле «Участников»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_members",
        "fun",
        "template",
        "{humans} людей + {bots} ботов",
        label="/serverstats: значение участников",
        placeholders=("humans", "bots"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_field_channels",
        "fun",
        "str",
        "Каналов",
        label="/serverstats: поле «Каналов»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_channels",
        "fun",
        "template",
        "{text} текстовых, {voice} голосовых",
        label="/serverstats: значение каналов",
        placeholders=("text", "voice"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_field_boosts",
        "fun",
        "str",
        "Бустов",
        label="/serverstats: поле «Бустов»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_boosts",
        "fun",
        "template",
        "{count} (ур. {tier})",
        label="/serverstats: значение бустов",
        placeholders=("count", "tier"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_field_created",
        "fun",
        "str",
        "Создан",
        label="/serverstats: поле «Создан»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.stats_field_owner",
        "fun",
        "str",
        "Владелец",
        label="/serverstats: поле «Владелец»",
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: /send (письмо через Попосю) ---
    _spec(
        "fun.send_bot",
        "fun",
        "str",
        "Ботам письма не ношу. У них нет души — читать нечем.",
        label="/send: получатель-бот",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_self",
        "fun",
        "str",
        "Письмо самому себе? Займись чем-нибудь. ✂️👁🖤",
        label="/send: письмо самому себе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_rate_limited",
        "fun",
        "str",
        "Я курьер, а не почтовое отделение. На сегодня с тебя хватит — позже.",
        label="/send: лимит на день",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_dm_anon",
        "fun",
        "template",
        "📨 **Анонимное письмо** (сервер «{guild}»):\n\n"
        "{text}\n\n"
        "-# Отправителя не выдам. Но я-то знаю, кто это. ✂️👁🖤",
        label="/send: текст анонимного письма (в ЛС)",
        placeholders=("guild", "text"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_dm_open",
        "fun",
        "template",
        "📨 **Письмо от {sender}** (сервер «{guild}»):\n\n{text}\n\n-# Передала лично. Попося ✂️👁🖤",
        label="/send: текст открытого письма (в ЛС)",
        placeholders=("sender", "guild", "text"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_forbidden",
        "fun",
        "template",
        "У {name} закрыты личные сообщения — письмо не доставить.",
        label="/send: у получателя закрыты ЛС",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.send_delivered",
        "fun",
        "template",
        "Доставлено ({mode}). Содержимое я, разумеется, прочитала.",
        label="/send: доставлено",
        placeholders=("mode",),
        allowed_modes=STATIC_MODES,
    ),
    # --- развлечения: /remind ---
    _spec(
        "fun.remind_scheduled",
        "fun",
        "template",
        "⏰ Напомню в ЛС {when}: {text}\n"
        "Проверь, что личные сообщения от участников сервера открыты.",
        label="/remind: напоминание поставлено",
        placeholders=("when", "text"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "fun.remind_dm",
        "fun",
        "template",
        "⏰ Ты просил напомнить: {text}",
        label="/remind: доставка напоминания (в ЛС)",
        placeholders=("text",),
        allowed_modes=STATIC_MODES,
    ),
]
