"""Фразы персоны: модерация: варны, муты, баны, антиспам, /say, /rage, ЛС."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- модерация: /say ---
    _spec(
        "moderation.say_no_perm",
        "moderation",
        "template",
        "Нет прав писать в {channel}.",
        label="/say: нет прав писать в канал",
        placeholders=("channel",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.say_sent",
        "moderation",
        "template",
        "Отправлено в {channel}.",
        label="/say: сообщение отправлено",
        placeholders=("channel",),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: антиспам ---
    _spec(
        "moderation.spam_warning",
        "moderation",
        "template",
        "{mention} — я всё вижу. Ещё раз так — помолчишь {minutes} мин. Это предупреждение. ✂️👁🖤",
        label="Антиспам: первое предупреждение",
        placeholders=("mention", "minutes"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.spam_muted",
        "moderation",
        "template",
        "{mention} — я предупреждала. {minutes} мин тишины. ✂️👁🖤",
        label="Антиспам: мут за повторный спам",
        placeholders=("mention", "minutes"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: варны ---
    _spec(
        "moderation.warn_bot",
        "moderation",
        "str",
        "Ботов не варним.",
        label="/warn: ботов не варним",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.warn_muted",
        "moderation",
        "template",
        "⚠️ {mention}: {count}/{threshold} варнов — мут на {minutes} мин, счётчик обнулён.",
        label="/warn: порог достигнут, мут",
        placeholders=("mention", "count", "threshold", "minutes"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.warn_added",
        "moderation",
        "template",
        "⚠️ {mention}: варн {count}/{threshold}. Причина: {reason}",
        label="/warn: предупреждение выдано",
        placeholders=("mention", "count", "threshold", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.warnings_none",
        "moderation",
        "template",
        "У {name} нет активных предупреждений.",
        label="/warnings: предупреждений нет",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.warnings_title",
        "moderation",
        "template",
        "⚠️ Предупреждения: {name} ({count}/{threshold})",
        label="/warnings: заголовок списка",
        placeholders=("name", "count", "threshold"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.warns_cleared",
        "moderation",
        "template",
        "Сброшено предупреждений у {mention}: {count}.",
        label="/clearwarns: сброшено",
        placeholders=("mention", "count"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: мут / анмут ---
    _spec(
        "moderation.muted",
        "moderation",
        "template",
        "🔇 {mention} замучен на {minutes} мин. Причина: {reason}",
        label="/mute: участник замучен",
        placeholders=("mention", "minutes", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.mute_failed",
        "moderation",
        "str",
        "Не получилось: нет права Timeout Members или роль участника выше моей.",
        label="/mute: не удалось (нет прав)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unmute_failed",
        "moderation",
        "str",
        "Не получилось снять мут.",
        label="/unmute: не удалось",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unmuted",
        "moderation",
        "template",
        "🔊 Мут снят с {mention}.",
        label="/unmute: мут снят",
        placeholders=("mention",),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: временные баны ---
    _spec(
        "moderation.ban_no_perm",
        "moderation",
        "str",
        "Нет права Ban Members (или роль участника выше моей).",
        label="/tempban: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.tempbanned",
        "moderation",
        "template",
        "🔨 {mention} забанен до {when}. Причина: {reason}",
        label="/tempban: забанен",
        placeholders=("mention", "when", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unban_bad_id",
        "moderation",
        "str",
        "Это не ID.",
        label="/unban: не ID",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unban_not_banned",
        "moderation",
        "str",
        "Этот пользователь не в бане.",
        label="/unban: не в бане",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unban_no_perm",
        "moderation",
        "str",
        "Нет права Ban Members.",
        label="/unban: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.unbanned",
        "moderation",
        "template",
        "✅ <@{user_id}> разбанен.",
        label="/unban: разбанен",
        placeholders=("user_id",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.bans_none",
        "moderation",
        "str",
        "Активных временных банов нет.",
        label="/bans: активных банов нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.bans_title",
        "moderation",
        "template",
        "🔨 Временные баны ({count})",
        label="/bans: заголовок списка",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.bans_row",
        "moderation",
        "template",
        "`{index}.` <@{user_id}> — до {when} ({reason})",
        label="/bans: строка списка",
        placeholders=("index", "user_id", "when", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: чистка и slowmode ---
    _spec(
        "moderation.clear_no_perm",
        "moderation",
        "str",
        "Нет права Manage Messages.",
        label="/clear: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.cleared",
        "moderation",
        "template",
        "🧹 Удалено сообщений: {count}.",
        label="/clear: удалено сообщений",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.slowmode_no_perm",
        "moderation",
        "str",
        "Нет права Manage Channels.",
        label="/slowmode: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.slowmode_off",
        "moderation",
        "str",
        "выключен",
        label="/slowmode: состояние «выключен»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.slowmode_on",
        "moderation",
        "template",
        "{seconds} c",
        label="/slowmode: состояние «N секунд»",
        placeholders=("seconds",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.slowmode_set",
        "moderation",
        "template",
        "🐢 Slowmode: {state}.",
        label="/slowmode: подтверждение",
        placeholders=("state",),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: /rage ---
    _spec(
        "moderation.rage_no_voice",
        "moderation",
        "str",
        "Он не в голосовом канале. Ярость откладывается.",
        label="/rage: цель не в войсе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.rage_start",
        "moderation",
        "template",
        "😤 Так. {mention}. Иди сюда.",
        label="/rage: начало",
        placeholders=("mention",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.rage_kicked",
        "moderation",
        "str",
        "Вышвырнула. Пусть подумает о своём поведении. ✂️👁🖤",
        label="/rage: кикнут",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.rage_no_perm",
        "moderation",
        "str",
        "Не хватило прав дожать (Move Members / Kick Members). Скучно.",
        label="/rage: не хватило прав",
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: /kick ---
    _spec(
        "moderation.kicked",
        "moderation",
        "template",
        "👢 {mention} вышвырнут с сервера. Причина: {reason}",
        label="/kick: участник кикнут",
        placeholders=("mention", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.kick_no_perm",
        "moderation",
        "str",
        "Нет права Kick Members (или роль участника выше моей).",
        label="/kick: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: постоянный /ban ---
    _spec(
        "moderation.banned",
        "moderation",
        "template",
        "🔨 {mention} забанен навсегда. Причина: {reason}",
        label="/ban: забанен навсегда",
        placeholders=("mention", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: эскалация варнов -> tempban рецидивисту ---
    _spec(
        "moderation.warn_tempbanned",
        "moderation",
        "template",
        "⚠️ {mention}: {count}/{threshold} и снова по кругу. Хватит — бан до {when}.",
        label="/warn: рецидив, tempban по эскалации",
        placeholders=("mention", "count", "threshold", "when"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: /history ---
    _spec(
        "moderation.history_none",
        "moderation",
        "template",
        "У {name} чистая история. Пока что.",
        label="/history: история пуста",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.history_title",
        "moderation",
        "template",
        "🗒️ История модерации: {name} ({count})",
        label="/history: заголовок",
        placeholders=("name", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.history_row",
        "moderation",
        "template",
        "`{when}` **{action}** — {reason} ({moderator})",
        label="/history: строка события",
        placeholders=("when", "action", "reason", "moderator"),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: антиспам (масс-упоминания и инвайты) ---
    _spec(
        "moderation.spam_mention",
        "moderation",
        "template",
        "{mention} — столько пингов разом? {minutes} мин тишины. ✂️👁🖤",
        label="Антиспам: масс-упоминания",
        placeholders=("mention", "minutes"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.spam_invite",
        "moderation",
        "template",
        "{mention} — чужие приглашения тут не нужны. Убрала, тебе варн.",
        label="Антиспам: чужой инвайт удалён",
        placeholders=("mention",),
        allowed_modes=STATIC_MODES,
    ),
    # --- модерация: ЛС наказанному (причина/срок) ---
    _spec(
        "moderation.dm_warned",
        "moderation",
        "template",
        "Тебе варн на «{guild}» ({count}/{threshold}). Причина: {reason}",
        label="ЛС: варн",
        placeholders=("guild", "count", "threshold", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.dm_muted",
        "moderation",
        "template",
        "На «{guild}» тебе {minutes} мин тишины. Причина: {reason}",
        label="ЛС: мут",
        placeholders=("guild", "minutes", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.dm_kicked",
        "moderation",
        "template",
        "Тебя убрали с «{guild}». Причина: {reason}",
        label="ЛС: кик",
        placeholders=("guild", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.dm_tempbanned",
        "moderation",
        "template",
        "Тебя забанили на «{guild}» до {when}. Причина: {reason}",
        label="ЛС: временный бан",
        placeholders=("guild", "when", "reason"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "moderation.dm_banned",
        "moderation",
        "template",
        "Тебя забанили на «{guild}» навсегда. Причина: {reason}",
        label="ЛС: постоянный бан",
        placeholders=("guild", "reason"),
        allowed_modes=STATIC_MODES,
    ),
]
