"""Фразы персоны: музыка: очередь, плеер, лайки, караоке, плейлисты, радио, вкусы."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- музыка: постановка в очередь и поиск ---
    _spec(
        "music.join_voice_first",
        "music",
        "str",
        "Сначала зайди в голосовой канал.",
        label="Нужно зайти в голосовой канал",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.add_prefix",
        "music",
        "str",
        "Добавила",
        label="Приставка «добавила в очередь»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.add_front_prefix",
        "music",
        "str",
        "Поставила первой",
        label="Приставка «поставила первой в очередь»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.spotify_playlist_needs_api",
        "music",
        "str",
        "Для плейлистов и альбомов Spotify нужен их API — задай "
        "SPOTIFY_CLIENT_ID и SPOTIFY_CLIENT_SECRET в .env. Пока могу только "
        "треки по ссылке.",
        label="Spotify: для плейлистов нужен API-ключ",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.spotify_playlist_failed",
        "music",
        "str",
        "Не получилось разобрать плейлист Spotify — попробуй ещё раз или кинь ссылку на трек.",
        label="Spotify: плейлист не разобрался",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.spotify_playlist_added",
        "music",
        "template",
        "{prefix} плейлист Spotify → YouTube: **{found}** из {total} треков.",
        label="Spotify: добавлен плейлист (найдено из всего)",
        placeholders=("prefix", "found", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.spotify_no_title",
        "music",
        "str",
        "Spotify не отдал название трека. Попробуй поиском.",
        label="Spotify: название трека не получено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.youtube_not_found",
        "music",
        "template",
        "На YouTube не нашлось: {query}",
        label="На YouTube ничего не нашлось по запросу",
        placeholders=("query",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.link_open_failed",
        "music",
        "template",
        "Не смогла открыть ссылку: {error}",
        label="Ссылку не удалось открыть",
        placeholders=("error",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.link_empty",
        "music",
        "str",
        "По ссылке ничего не нашлось.",
        label="По ссылке ничего не нашлось",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.added_playlist_tracks",
        "music",
        "template",
        "{prefix}: **{count}** треков из плейлиста.",
        label="Добавлено N треков из плейлиста",
        placeholders=("prefix", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.search_empty",
        "music",
        "str",
        "Ничего не нашла по запросу.",
        label="Поиск: ничего не нашлось",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.search_results",
        "music",
        "template",
        "Нашла {count} — выбери трек:",
        label="Поиск: приглашение выбрать трек",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: очередь и история ---
    _spec(
        "music.queue_empty",
        "music",
        "str",
        "Очередь пуста.",
        label="Очередь пуста",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.history_empty",
        "music",
        "str",
        "История пуста.",
        label="История треков пуста",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.history_title",
        "music",
        "template",
        "🕘 История ({count})",
        label="Заголовок истории треков",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: сохранение очереди в плейлист ---
    _spec(
        "music.save_queue_empty",
        "music",
        "str",
        "Очередь пуста — нечего сохранять.",
        label="Сохранение очереди: очередь пуста",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_saved",
        "music",
        "template",
        "💾 Сохранила «{name}» — {count} треков.",
        label="Плейлист сохранён",
        placeholders=("name", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_limit",
        "music",
        "template",
        "Лимит плейлистов на сервере ({limit}) исчерпан.",
        label="Лимит плейлистов исчерпан",
        placeholders=("limit",),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: skip/shuffle/remove/seek ---
    _spec(
        "music.nothing_playing",
        "music",
        "str",
        "Сейчас ничего не играет.",
        label="Сейчас ничего не играет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.skipped",
        "music",
        "str",
        "⏭️ Пропустил.",
        label="Трек пропущен",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.nothing_to_shuffle",
        "music",
        "str",
        "Перемешивать нечего.",
        label="Перемешивать нечего",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.shuffled",
        "music",
        "str",
        "🔀 Перемешал очередь.",
        label="Очередь перемешана",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.remove_no_track",
        "music",
        "template",
        "В очереди нет трека №{position} — их всего {count}.",
        label="Удаление: такого номера в очереди нет",
        placeholders=("position", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.removed",
        "music",
        "template",
        "🗑️ Убрала из очереди: **{title}**.",
        label="Трек убран из очереди",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.seek_bad_position",
        "music",
        "str",
        "Не поняла позицию. Пиши «1:23», «83» или «1:02:03».",
        label="Перемотка: не разобрать позицию",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.seek_live",
        "music",
        "str",
        "Живой эфир не перемотать.",
        label="Перемотка: живой эфир не перемотать",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.seek_out_of_range",
        "music",
        "template",
        "За пределами трека — он длиной {limit}.",
        label="Перемотка: за пределами трека",
        placeholders=("limit",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.seeked",
        "music",
        "template",
        "⏩ Перемотала на `{position}`.",
        label="Трек перемотан",
        placeholders=("position",),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: stop/pause/resume/volume/nowplaying/leave ---
    _spec(
        "music.not_playing_idle",
        "music",
        "str",
        "Я и так ничего не играю.",
        label="/stop: и так ничего не играю",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.stopped",
        "music",
        "str",
        "⏹️ Остановила и вышла.",
        label="Остановлено и вышла",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_stop",
        "music",
        "str",
        "⏹️ Остановлено командой /stop.",
        label="Плеер: причина остановки командой /stop",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.pause_nothing",
        "music",
        "str",
        "Нечего ставить на паузу.",
        label="Пауза: нечего ставить на паузу",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.already_paused",
        "music",
        "str",
        "Уже на паузе.",
        label="Уже на паузе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.paused",
        "music",
        "str",
        "⏸️ Пауза.",
        label="Поставлено на паузу",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.resume_nothing",
        "music",
        "str",
        "Продолжать нечего.",
        label="Продолжать нечего",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.resumed",
        "music",
        "str",
        "▶️ Продолжаю.",
        label="Воспроизведение продолжено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.volume_set",
        "music",
        "template",
        "🔊 Громкость: {value}%.",
        label="Громкость установлена",
        placeholders=("value",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.nowplaying_silence",
        "music",
        "str",
        "Тишина. Наслаждайся.",
        label="/nowplaying: тишина",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.not_in_voice",
        "music",
        "str",
        "Меня и так нет в войсе.",
        label="/leave: меня и так нет в войсе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.left",
        "music",
        "str",
        "👋 Ушла.",
        label="Вышла из канала",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_leave",
        "music",
        "str",
        "👋 Вышла по команде /leave.",
        label="Плеер: причина выхода командой /leave",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: тексты и караоке ---
    _spec(
        "music.karaoke_on",
        "music",
        "str",
        "🎤 Караоке включено.",
        label="Караоке включено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.karaoke_premium",
        "music",
        "str",
        "Караоке-режим — уже про «свой дом». Что открывает подписка — в `/premium` 🖤",
        label="Караоке: только Premium",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.karaoke_no_synced",
        "music",
        "str",
        "Синхронного текста для этого трека нет — попробуй `/lyrics` без live.",
        label="Караоke: синхронного текста нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.lyrics_not_found",
        "music",
        "str",
        "Текста не нашла. Или его нет, или назван криво.",
        label="Текст трека не найден",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.lrc_bad_file",
        "music",
        "str",
        "Нужен файл .lrc (до 200 КБ).",
        label="Загрузка .lrc: нужен файл .lrc",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.lrc_download_failed",
        "music",
        "str",
        "Не смогла скачать файл.",
        label="Загрузка .lrc: файл не скачался",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.lrc_no_timecodes",
        "music",
        "str",
        "В файле нет строк с таймкодами `[mm:ss.xx]` — это не похоже на .lrc.",
        label="Загрузка .lrc: нет таймкодов",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.lrc_accepted",
        "music",
        "str",
        "📄 Приняла твой текст. Жми 📜 в плеере или `/lyrics live` — караоке по нему.",
        label="Загрузка .lrc: файл принят",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: плейлисты сервера ---
    _spec(
        "music.playlist_save_empty",
        "music",
        "str",
        "Сохранять нечего — очередь пуста.",
        label="/playlist save: очередь пуста",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_not_found",
        "music",
        "str",
        "Такого плейлиста нет.",
        label="Плейлист не найден",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_played",
        "music",
        "template",
        "▶️ Плейлист «{name}»: {count} треков в очереди.",
        label="Плейлист поставлен в очередь",
        placeholders=("name", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_list_empty",
        "music",
        "str",
        "Плейлистов пока нет — `/playlist save`.",
        label="Список плейлистов пуст",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_list_title",
        "music",
        "template",
        "💾 Плейлисты ({count})",
        label="Заголовок списка плейлистов",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_deleted",
        "music",
        "template",
        "🗑️ «{name}» удалён.",
        label="Плейлист удалён",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.playlist_delete_forbidden",
        "music",
        "str",
        "Удалять может только автор плейлиста или администратор.",
        label="Удаление плейлиста: нет прав",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: совместимость вкусов (/taste) ---
    _spec(
        "music.taste_bot",
        "music",
        "str",
        "У ботов нет вкуса. Проверено на себе. Хотя у меня — есть.",
        label="/taste: сравнение с ботом",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_self",
        "music",
        "str",
        "Сравнивать себя с собой? 100%. Поздравляю, нарцисс.",
        label="/taste: сравнение с собой",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_whose_you",
        "music",
        "str",
        "у тебя",
        label="/taste: «у тебя» (для «нет лайков»)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_whose_other",
        "music",
        "template",
        "у {name}",
        label="/taste: «у <имя>» (для «нет лайков»)",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_no_likes",
        "music",
        "template",
        "Сравнивать нечего — {whose} пока нет лайков. ❤️ на плеере в помощь.",
        label="/taste: не с чем сравнивать",
        placeholders=("whose",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_lines",
        "music",
        "dict",
        {
            "suspicious": "Подозрительно. Один из вас явно списывал. ✂️👁🖤",
            "high": "Серьёзно? Вам пора вести совместный плейлист.",
            "mid": "Неплохо. Есть о чём поговорить за виски.",
            "low": "Слабое пересечение. Но хоть что-то.",
            "none": "Ноль общих треков. Вы вообще на одном сервере сидите?",
        },
        label="/taste: вердикт по проценту (suspicious/high/mid/low/none)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_common_header",
        "music",
        "str",
        "**Общие треки:**",
        label="/taste: заголовок общих треков",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_common_more",
        "music",
        "template",
        "…и ещё {count}",
        label="/taste: «…и ещё N» общих треков",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_title",
        "music",
        "str",
        "🎧 Совместимость вкусов",
        label="/taste: заголовок эмбеда",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.taste_footer",
        "music",
        "template",
        "Лайков: {mine} у тебя · {theirs} у {other}",
        label="/taste: футер со счётом лайков",
        placeholders=("mine", "theirs", "other"),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: радио ---
    _spec(
        "music.radio_off",
        "music",
        "str",
        "📻 Радио выключено.",
        label="Радио выключено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.radio_on",
        "music",
        "str",
        "📻 Радио включено: пустая очередь — не повод для тишины. "
        "Беру треки из лайков тех, кто в войсе, или из плейлистов сервера.",
        label="Радио включено",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.radio_nothing",
        "music",
        "str",
        "Пока нечего играть: ни лайков у слушателей, ни плейлистов.",
        label="Радио: нечего играть",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: лайки ---
    _spec(
        "music.like_liked",
        "music",
        "template",
        "❤️ В твоих лайках: **{title}** — `/liked`",
        label="Трек добавлен в лайки",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.like_unliked",
        "music",
        "template",
        "💔 Убрала из лайков: **{title}**",
        label="Трек убран из лайков",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.like_limit",
        "music",
        "template",
        "Лимит лайков ({limit}) исчерпан — почисти список через `/liked remove`.",
        label="Лимит лайков исчерпан",
        placeholders=("limit",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_list_bot",
        "music",
        "str",
        "У ботов нет лайков. И вкуса.",
        label="/liked list: у ботов нет лайков",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_list_empty_self",
        "music",
        "str",
        "Пусто. Жми ❤️ на плеере, когда играет что-то стоящее.",
        label="/liked list: своих лайков нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_list_empty_other",
        "music",
        "template",
        "У {name} пока нет лайков.",
        label="/liked list: чужих лайков нет",
        placeholders=("name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_play_dead",
        "music",
        "str",
        "Не смогла оживить этот трек: видео умерло, а поиск замены не дал. "
        "Убери его через `/liked remove`.",
        label="/liked play: трек не оживить",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_play_added",
        "music",
        "template",
        "Добавила из лайков: **{title}**",
        label="/liked play: трек добавлен",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_all_empty",
        "music",
        "str",
        "Лайков пока нет.",
        label="/liked all: лайков нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_all_note",
        "music",
        "template",
        " (первые {limit})",
        label="/liked all: приписка про лимит",
        placeholders=("limit",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_all_queued",
        "music",
        "template",
        "▶️ Все лайки в очереди: **{count}** треков{note}. Умершие видео пропущу сама.",
        label="/liked all: все лайки в очереди",
        placeholders=("count", "note"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_remove_done",
        "music",
        "str",
        "💔 Убрала.",
        label="/liked remove: трек убран",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_remove_none",
        "music",
        "str",
        "Такого трека в твоих лайках нет.",
        label="/liked remove: трека нет в лайках",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_saved",
        "music",
        "template",
        "💾 Плейлист «{name}» из твоих лайков — {count} треков.",
        label="/liked save: плейлист из лайков сохранён",
        placeholders=("name", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_save_empty",
        "music",
        "str",
        "Лайков пока нет — сохранять нечего.",
        label="/liked save: лайков нет",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: плеер (эмбед сообщения-плеера) ---
    _spec(
        "music.player_title",
        "music",
        "str",
        "🎵 Плеер",
        label="Плеер: заголовок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_empty",
        "music",
        "str",
        "Очередь пуста. Добавь трек через `/play`.",
        label="Плеер: пустая очередь",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_now_title",
        "music",
        "str",
        "▶️ Сейчас играет",
        label="Плеер: заголовок «сейчас играет»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_paused_title",
        "music",
        "str",
        "⏸️ Пауза",
        label="Плеер: заголовок на паузе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_live",
        "music",
        "str",
        "🔴 Прямой эфир",
        label="Плеер: метка прямого эфира",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_volume",
        "music",
        "str",
        "Громкость",
        label="Плеер: поле «Громкость»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_repeat",
        "music",
        "str",
        "Повтор",
        label="Плеер: поле «Повтор»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_requester",
        "music",
        "str",
        "Заказал",
        label="Плеер: поле «Заказал»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_radio",
        "music",
        "str",
        "Радио",
        label="Плеер: поле «Радио»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_radio_on",
        "music",
        "str",
        "📻 вкл",
        label="Плеер: значение «Радио включено»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.field_next",
        "music",
        "str",
        "Далее",
        label="Плеер: поле «Далее»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_more",
        "music",
        "template",
        "…и ещё {rest}",
        label="Плеер: «…и ещё N» в очереди",
        placeholders=("rest",),
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: сессии и авто-выход ---
    _spec(
        "music.no_longer_in_voice",
        "music",
        "str",
        "Ты уже не в голосовом канале.",
        label="Постановка: ты уже вышел из войса",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.already_playing_elsewhere",
        "music",
        "str",
        "Я уже играю в другом голосовом канале.",
        label="Постановка: уже играю в другом канале",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.fail_phrases",
        "music",
        "list",
        [
            "«{title}» включить не вышло — то ли удалили, то ли YouTube капризничает. Пропускаю.",
            "«{title}» не запускается, хоть тресни. Ставь другую.",
            "С «{title}» что-то не так — не отдаётся. Дальше по очереди.",
        ],
        label="Трек не заиграл: реплика (случайная)",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.idle_prompt",
        "music",
        "template",
        "Очередь закончилась. Включить что-то ещё? `/play` — или через {minutes} мин я ухожу. ✂️👁🖤",
        label="Простой: предложение включить ещё перед выходом",
        placeholders=("minutes",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_idle",
        "music",
        "str",
        "💤 Ушла: тишина.",
        label="Плеер: причина выхода по простою",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_kicked",
        "music",
        "str",
        "Меня отключили от канала.",
        label="Плеер: причина — отключили от канала",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_all_left",
        "music",
        "str",
        "Все вышли из канала — ушла и я.",
        label="Плеер: причина — все вышли из канала",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_shutdown",
        "music",
        "str",
        "Бот выключается.",
        label="Плеер: причина — бот выключается",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: караоке (сервис текстов) ---
    _spec(
        "music.karaoke_footer",
        "music",
        "template",
        "{duration} · абзац {index}/{total} · lrclib.net",
        label="Караоке: футер (позиция/абзац)",
        placeholders=("duration", "index", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.karaoke_off",
        "music",
        "str",
        "📜 Караоке выключено.",
        label="Караоке выключено (кнопка плеера)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.karaoke_no_text",
        "music",
        "str",
        "Текста для этого трека не нашла.",
        label="Караоке: текста нет (кнопка плеера)",
        allowed_modes=STATIC_MODES,
    ),
    # --- музыка: виджеты (поиск/очередь/лайки/кнопки плеера) ---
    _spec(
        "music.added_again",
        "music",
        "template",
        "Добавила снова: **{title}**",
        label="История: трек добавлен снова",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.queue_title",
        "music",
        "template",
        "🎶 Очередь ({count})",
        label="Очередь: заголовок эмбеда",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.queue_footer",
        "music",
        "template",
        "Стр. {page}/{total} · всего ~{duration}",
        label="Очередь: футер (страница/длительность)",
        placeholders=("page", "total", "duration"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.queue_only_current",
        "music",
        "str",
        "В очереди пусто — играет только текущий трек.",
        label="Очередь: пусто, играет только текущий",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_title_self",
        "music",
        "template",
        "❤️ Твои лайки ({count})",
        label="Лайки: заголовок «свои»",
        placeholders=("count",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_title_other",
        "music",
        "template",
        "❤️ Лайки {name} ({count})",
        label="Лайки: заголовок «чужие»",
        placeholders=("name", "count"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_footer",
        "music",
        "template",
        "Страница {page}/{total} · меню ниже — включить трек",
        label="Лайки: футер (страница)",
        placeholders=("page", "total"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.player_inactive",
        "music",
        "str",
        "Плеер уже не активен.",
        label="Кнопки плеера: плеер не активен",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.buttons_voice_only",
        "music",
        "str",
        "Кнопки — для тех, кто в голосовом канале со мной.",
        label="Кнопки плеера: только для тех, кто в войсе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.history_empty_back",
        "music",
        "str",
        "История пуста — некуда назад.",
        label="Кнопки плеера: история пуста (назад)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.cleanup_stop_button",
        "music",
        "str",
        "⏹️ Остановлено.",
        label="Плеер: причина остановки (кнопка ⏹️)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.shuffle_empty_player",
        "music",
        "str",
        "Перемешивать нечего — в очереди пусто.",
        label="Кнопки плеера: перемешивать нечего",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_play_dead_view",
        "music",
        "str",
        "Не смогла оживить этот трек: видео умерло, замена не нашлась.",
        label="Лайки (виджет): трек не оживить",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "music.liked_view_added",
        "music",
        "template",
        "Добавила: **{title}**",
        label="Лайки (виджет): трек добавлен",
        placeholders=("title",),
        allowed_modes=STATIC_MODES,
    ),
]
