"""Фразы персоны: отношения: /rank, /leaderboard, админ-группа, «остаться/уйти»."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- отношения: /rank ---
    _spec(
        "relationship.rank_no_status",
        "relationship",
        "str",
        "без статуса (она тебя ещё не заметила)",
        label="/rank: статуса ещё нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.rank_points",
        "relationship",
        "template",
        "**Очки:** {points}",
        label="/rank: строка очков",
        placeholders=("points",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.rank_status",
        "relationship",
        "template",
        "**Статус:** {status}",
        label="/rank: строка статуса",
        placeholders=("status",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.rank_to_next",
        "relationship",
        "template",
        "**До следующего статуса:** {remaining} очков",
        label="/rank: сколько до следующего статуса",
        placeholders=("remaining",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.rank_exclusive_hint",
        "relationship",
        "str",
        "Дальше — только место Единственного. Его придётся отвоевать.",
        label="/rank: подсказка про Единственного",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.rank_frozen",
        "relationship",
        "str",
        "⚠️ Начисление очков заморожено администратором.",
        label="/rank: очки заморожены",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.no_status_short",
        "relationship",
        "str",
        "без статуса",
        label="/leaderboard·/relationship: короткое «без статуса»",
        allowed_modes=STATIC_MODES,
    ),
    # --- отношения: /leaderboard ---
    _spec(
        "relationship.leaderboard_empty",
        "relationship",
        "str",
        "Пока никто не заработал ни очка. Скучные.",
        label="/leaderboard: таблица пуста",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.leaderboard_title",
        "relationship",
        "str",
        "🏆 Кто ближе всех к Попосе",
        label="/leaderboard: заголовок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.leaderboard_footer",
        "relationship",
        "str",
        "Очки за общение с ней · титул Единственного — у лидера от 350",
        label="/leaderboard: футер",
        allowed_modes=STATIC_MODES,
    ),
    # --- отношения: админ-группа ---
    _spec(
        "relationship.points_set",
        "relationship",
        "template",
        "У {mention} теперь {points} очков ({status}).",
        label="/relationship points: очки заданы",
        placeholders=("mention", "points", "status"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.freeze_frozen",
        "relationship",
        "str",
        "заморожено ❄️",
        label="/relationship freeze: состояние «заморожено»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.freeze_active",
        "relationship",
        "str",
        "снова идёт ▶️",
        label="/relationship freeze: состояние «идёт»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.freeze_set",
        "relationship",
        "template",
        "Начисление очков для {mention}: {state}",
        label="/relationship freeze: подтверждение",
        placeholders=("mention", "state"),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "relationship.sync_done",
        "relationship",
        "str",
        "Роль сверена с очками.",
        label="/relationship sync: роль сверена",
        allowed_modes=STATIC_MODES,
    ),
]
