"""Фразы персоны: каморки (временные войсы): создание, панели, кнопки."""

from src.application.persona.phrases._base import STATIC_MODES, _spec

SPECS = [
    # --- каморки (tempvoice): создание и отказы ---
    _spec(
        "tempvoice.channel_name",
        "tempvoice",
        "template",
        "Каморка {display_name}",
        label="Каморка: имя канала",
        placeholders=("display_name",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.cap_reached",
        "tempvoice",
        "str",
        "Каморок на сервере уже столько, что я в них путаюсь. Подожди, пока освободится хоть одна.",
        label="Каморка: лимит на сервере исчерпан",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.no_manage_perms",
        "tempvoice",
        "str",
        "Я бы сделала тебе каморку, но мне не выдали право управлять "
        "каналами. Это к админу, не ко мне.",
        label="Каморка: нет права управлять каналами",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.no_move_perms",
        "tempvoice",
        "str",
        "Каморка была готова, но перенести тебя туда мне не позволили — "
        "нужно право «Перемещать участников». Убрала обратно, чтобы не мусорить.",
        label="Каморка: нет права перемещать участников",
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: панель хаба ---
    _spec(
        "tempvoice.hub_title",
        "tempvoice",
        "str",
        "Каморки",
        label="Хаб каморок: заголовок",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.hub_intro",
        "tempvoice",
        "str",
        "Зайди в этот канал — получишь свою каморку. Выйдут все — уберу "
        "за вами, будто ничего и не было.",
        label="Хаб каморок: описание",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.hub_how",
        "tempvoice",
        "str",
        "Кнопки ниже действуют на ту каморку, где ты сейчас сидишь.\n"
        "Такие же лежат в чате самой каморки — там ещё видно, что с ней происходит.",
        label="Хаб каморок: как пользоваться",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.hub_field_buttons",
        "tempvoice",
        "str",
        "Кнопки",
        label="Хаб каморок: поле «Кнопки»",
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: панель каморки ---
    _spec(
        "tempvoice.panel_intro",
        "tempvoice",
        "str",
        "Твоя каморка. Что с ней делать — решаешь ты.",
        label="Панель каморки: описание",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.field_door",
        "tempvoice",
        "str",
        "Дверь",
        label="Панель каморки: поле «Дверь»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.door_locked",
        "tempvoice",
        "str",
        "🔒 закрыта",
        label="Панель каморки: дверь закрыта",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.door_open",
        "tempvoice",
        "str",
        "🔓 открыта",
        label="Панель каморки: дверь открыта",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.field_visibility",
        "tempvoice",
        "str",
        "Видимость",
        label="Панель каморки: поле «Видимость»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.vis_hidden",
        "tempvoice",
        "str",
        "🙈 скрыта",
        label="Панель каморки: скрыта",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.vis_shown",
        "tempvoice",
        "str",
        "👁 видна всем",
        label="Панель каморки: видна всем",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.field_slots",
        "tempvoice",
        "str",
        "Мест",
        label="Панель каморки: поле «Мест»",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.slots_unlimited",
        "tempvoice",
        "str",
        "без лимита",
        label="Панель каморки: без лимита мест",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.field_owner",
        "tempvoice",
        "str",
        "Хозяин",
        label="Панель каморки: поле «Хозяин»",
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: отказы кнопок ---
    _spec(
        "tempvoice.not_temp",
        "tempvoice",
        "str",
        "Это обычный канал, а не каморка. Кнопки тут ни при чём.",
        label="Каморка: это не каморка",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.not_in_voice",
        "tempvoice",
        "str",
        "Ты вообще не в войсе. Зайди в свою каморку — потом нажимай.",
        label="Каморка: ты не в войсе",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.not_in_temp",
        "tempvoice",
        "str",
        "Ты сидишь в обычном канале, а не в каморке. Кнопки — про каморки.",
        label="Каморка: ты в обычном канале",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.action_failed",
        "tempvoice",
        "str",
        "Не вышло. Либо Discord не в духе, либо мне не хватает прав.",
        label="Каморка: действие не удалось",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.not_owner",
        "tempvoice",
        "template",
        "Каморка не твоя — хозяин тут <@{owner_id}>. Если он ушёл, а ты внутри — жми 👑 Забрать.",
        label="Каморка: ты не хозяин",
        placeholders=("owner_id",),
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: «Забрать» ---
    _spec(
        "tempvoice.claim_refusals",
        "tempvoice",
        "dict",
        {
            "already_owner": "Это и так твоя каморка. Расслабься.",
            "owner_present": "Хозяин на месте. Забирать чужое при живом хозяине — не ко мне.",
            "not_in_channel": "Сначала зайди внутрь, потом забирай.",
            "not_temp": "Это обычный канал, а не каморка. Кнопки тут ни при чём.",
        },
        label="Каморка: отказы «Забрать» (already_owner/owner_present/not_in_channel/not_temp)",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.claimed",
        "tempvoice",
        "template",
        "Каморка теперь твоя. <@{previous_owner_id}> ушёл — бывает.",
        label="Каморка: забрана",
        placeholders=("previous_owner_id",),
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: имя и лимит ---
    _spec(
        "tempvoice.rename_too_soon",
        "tempvoice",
        "template",
        "Discord разрешает переименовать канал дважды за 10 минут — это "
        "не моя прихоть. Следующее имя приму через {seconds} сек.",
        label="Каморка: переименование слишком часто",
        placeholders=("seconds",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.limit_bad",
        "tempvoice",
        "str",
        "Нужно целое число от 0 до 99. Ноль — значит без лимита.",
        label="Каморка: неверный лимит мест",
        allowed_modes=STATIC_MODES,
    ),
    # --- каморки: выгнать / впустить / забанить ---
    _spec(
        "tempvoice.kicked",
        "tempvoice",
        "template",
        "<@{user_id}> отправлен за дверь.",
        label="Каморка: участник выгнан",
        placeholders=("user_id",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.permitted",
        "tempvoice",
        "template",
        "<@{user_id}> может заходить, даже когда закрыто.",
        label="Каморка: участник впущен",
        placeholders=("user_id",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.blocked",
        "tempvoice",
        "template",
        "<@{user_id}> сюда больше не войдёт.",
        label="Каморка: участник забанен",
        placeholders=("user_id",),
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.not_here",
        "tempvoice",
        "str",
        "Его тут нет — выгонять некого.",
        label="Каморка: участника тут нет",
        allowed_modes=STATIC_MODES,
    ),
    _spec(
        "tempvoice.self_target",
        "tempvoice",
        "str",
        "Себя? Нет. Придумай что-нибудь получше.",
        label="Каморка: нельзя выбрать себя",
        allowed_modes=STATIC_MODES,
    ),
]
